/** Curated IANA timezones for the Availability schedule, common zones only. */
export const TIMEZONES: Array<{ value: string; label: string }> = [
  { value: "UTC", label: "(GMT +0:00) Coordinated Universal Time" },
  { value: "Europe/London", label: "(GMT +0:00) London" },
  { value: "Europe/Dublin", label: "(GMT +0:00) Dublin" },
  { value: "Europe/Lisbon", label: "(GMT +0:00) Lisbon" },
  { value: "Europe/Rome", label: "(GMT +1:00) Rome" },
  { value: "Europe/Paris", label: "(GMT +1:00) Paris" },
  { value: "Europe/Madrid", label: "(GMT +1:00) Madrid" },
  { value: "Europe/Berlin", label: "(GMT +1:00) Berlin" },
  { value: "Europe/Amsterdam", label: "(GMT +1:00) Amsterdam" },
  { value: "Europe/Athens", label: "(GMT +2:00) Athens" },
  { value: "Europe/Helsinki", label: "(GMT +2:00) Helsinki" },
  { value: "Europe/Bucharest", label: "(GMT +2:00) Bucharest" },
  { value: "Europe/Istanbul", label: "(GMT +3:00) Istanbul" },
  { value: "Europe/Moscow", label: "(GMT +3:00) Moscow" },
  { value: "Asia/Dubai", label: "(GMT +4:00) Dubai" },
  { value: "Asia/Karachi", label: "(GMT +5:00) Karachi" },
  { value: "Asia/Kolkata", label: "(GMT +5:30) Mumbai, New Delhi" },
  { value: "Asia/Dhaka", label: "(GMT +6:00) Dhaka" },
  { value: "Asia/Bangkok", label: "(GMT +7:00) Bangkok" },
  { value: "Asia/Shanghai", label: "(GMT +8:00) Beijing, Shanghai" },
  { value: "Asia/Singapore", label: "(GMT +8:00) Singapore" },
  { value: "Asia/Hong_Kong", label: "(GMT +8:00) Hong Kong" },
  { value: "Asia/Tokyo", label: "(GMT +9:00) Tokyo" },
  { value: "Asia/Seoul", label: "(GMT +9:00) Seoul" },
  { value: "Australia/Sydney", label: "(GMT +10:00) Sydney" },
  { value: "Pacific/Auckland", label: "(GMT +12:00) Auckland" },
  { value: "Atlantic/Azores", label: "(GMT -1:00) Azores" },
  { value: "America/Noronha", label: "(GMT -2:00) Fernando de Noronha" },
  { value: "America/Sao_Paulo", label: "(GMT -3:00) São Paulo" },
  { value: "America/Argentina/Buenos_Aires", label: "(GMT -3:00) Buenos Aires" },
  { value: "America/Halifax", label: "(GMT -4:00) Halifax" },
  { value: "America/New_York", label: "(GMT -5:00) New York" },
  { value: "America/Toronto", label: "(GMT -5:00) Toronto" },
  { value: "America/Chicago", label: "(GMT -6:00) Chicago" },
  { value: "America/Mexico_City", label: "(GMT -6:00) Mexico City" },
  { value: "America/Denver", label: "(GMT -7:00) Denver" },
  { value: "America/Los_Angeles", label: "(GMT -8:00) Los Angeles" },
  { value: "Pacific/Honolulu", label: "(GMT -10:00) Honolulu" },
];
